services:

  backend:
    build: ./mysite
    container_name: backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy  
    restart: always
    ports: 
      - 80:8000
    networks:
      - proyecto

  frontend:
    build: ./reactapp 
    container_name: frontend
    ports:
      - 8080:5173 
    depends_on:
      - backend
    networks:
      - proyecto
    
    
  db:
    image: mysql
    container_name: app_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      #- ./database:/var/lib/mysql
      - db_data:/var/lib/mysql
    ports: 
      - 3306:3306
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5
    networks:
      - proyecto

  php:
    depends_on:
      - db
    container_name: app_php
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
    networks:
      - proyecto
       
networks:
  proyecto:
    name: app_network
    
    
volumes:
  db_data:
    name: volumen1