# Generated by Django 4.2.7 on 2024-03-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaCar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
    ]
