# Generated by Django 4.2.7 on 2024-04-04 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConectaCar', '0004_alter_reserva_fecha_fin_alter_reserva_fecha_inicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Alquiler',
        ),
    ]
