# Generated by Django 4.2.7 on 2024-04-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaCar', '0005_rename_reserva_alquiler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='precio_por_dia',
            new_name='precio_por_hora',
        ),
    ]
