# Generated by Django 4.2.7 on 2024-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaCar', '0006_rename_precio_por_dia_vehicle_precio_por_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='numero_plazas',
            field=models.PositiveIntegerField(default=5, verbose_name='Número de plazas'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='potencia',
            field=models.IntegerField(help_text='Número de caballos de fuerza (CV)', null=True),
        ),
    ]
