# Generated by Django 4.2.11 on 2024-05-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaCar', '0007_vehicle_numero_plazas_vehicle_potencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='potencia',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='autonomia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Autonomía estimada del vehículo en kilómetros.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometraje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilómetros que ha recorrido el vehículo.', max_digits=10, null=True),
        ),
    ]
