# Generated by Django 4.2.11 on 2024-06-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaCar', '0011_reserva_precio_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='cliente',
            new_name='solicitante',
        ),
    ]
