# Generated by Django 4.2.11 on 2024-06-03 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConectaCar', '0012_rename_cliente_alquiler_solicitante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('activo', 'Activo'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedade', to=settings.AUTH_USER_MODEL),
        ),
    ]
