# Generated by Django 4.2.11 on 2024-06-03 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConectaCar', '0013_remove_alquiler_reserva_remove_reserva_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
