# Generated by Django 4.2.11 on 2024-06-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaCar', '0014_alter_alquiler_propietario_delete_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('activo', 'Activo'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
